import { useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Html, Line, OrbitControls } from '@react-three/drei';
import * as THREE from 'three';
import type { OrbitControls as OrbitImpl } from 'three-stdlib';
import type { Box, Pillar, PillarSet, Point } from '../core/types';
export const boxColor=(label:string)=>label==='Car'?'#ffb267':label==='Cyclist'?'#c8a2ff':'#70efd1';
const pos=(p:{x:number;y:number;z:number}):[number,number,number]=>[p.x,p.z,-p.y];
interface Props { points:Point[]; boxes:Box[]; set:PillarSet; step:number; selectedPillar?:Pillar; selectedPoint:number|null; selectedBox:string|null; onPoint:(i:number)=>void; onBox:(id:string)=>void; top:boolean; reset:number; voxel:boolean; showBoxes:boolean; showLabels:boolean; image:Float32Array; channel:number; model:boolean }
function Cloud({points,set,step,selectedPillar,selectedPoint,onPoint}:Props){
  const {positions,colors}=useMemo(()=>{const positions=new Float32Array(points.length*3),colors=new Float32Array(points.length*3);const c=new THREE.Color();points.forEach((p,i)=>{positions.set(pos(p),i*3);const chosen=selectedPillar?.indices.includes(i);if(step===3||step===4)c.set(chosen?'#ffb267':'#173345');else if(step===2&&chosen)c.set('#ffc077');else if(p.object==='road'||p.object==='curb'||p.object==='marking')c.set(p.r>.55?'#8bbccb':'#36677e');else if(p.object?.includes('ped'))c.set('#7cf2ce');else if(p.object?.includes('cyclist'))c.set('#c6a6ff');else c.set(p.z>1?'#b9f5ff':'#45d4ec');colors.set([c.r,c.g,c.b],i*3);});return{positions,colors};},[points,step,selectedPillar]);
  return <><points onClick={e=>{e.stopPropagation();if(e.index!==undefined)onPoint(e.index);}}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/><bufferAttribute attach="attributes-color" args={[colors,3]}/></bufferGeometry><pointsMaterial size={step===3?.055:.065} vertexColors sizeAttenuation transparent opacity={.95}/></points>{selectedPoint!==null&&points[selectedPoint]&&<mesh position={pos(points[selectedPoint])}><sphereGeometry args={[.055,12,12]}/><meshBasicMaterial color="#fff2cd"/></mesh>}{set.pillars.length===0&&null}</>;
}
function Columns({set,selectedPillar,voxel,focus=false}:{set:PillarSet;selectedPillar?:Pillar;voxel:boolean;focus?:boolean}){
  const selectedGeometry=useMemo(()=>new THREE.BoxGeometry(set.size,set.bounds.zmax-set.bounds.zmin,set.size),[set.size,set.bounds]);useEffect(()=>()=>selectedGeometry.dispose(),[selectedGeometry]);
  const vertices=useMemo(()=>{const a:number[]=[];const edge=(p:number[],q:number[])=>a.push(...p,...q);const z0=set.bounds.zmin,z1=set.bounds.zmax;for(const p of set.pillars){if(p.indices.length<2||(focus&&p.key!==selectedPillar?.key))continue;const x=p.cx-set.size/2,z=-p.cy-set.size/2,s=set.size;
    for(const [dx,dz] of [[0,0],[s,0],[0,s],[s,s]])edge([x+dx,z0,z+dz],[x+dx,z1,z+dz]);
    for(const h of [z0,z1]){edge([x,h,z],[x+s,h,z]);edge([x+s,h,z],[x+s,h,z+s]);edge([x+s,h,z+s],[x,h,z+s]);edge([x,h,z+s],[x,h,z]);}
    if(voxel&&selectedPillar&&Math.abs(p.cx-selectedPillar.cx)<1.2&&Math.abs(p.cy-selectedPillar.cy)<1.2)for(let h=z0+s;h<z1;h+=s){edge([x,h,z],[x+s,h,z]);edge([x+s,h,z],[x+s,h,z+s]);edge([x+s,h,z+s],[x,h,z+s]);edge([x,h,z+s],[x,h,z]);}
  }return new Float32Array(a);},[set,voxel,selectedPillar,focus]);
  return <><lineSegments><bufferGeometry><bufferAttribute attach="attributes-position" args={[vertices,3]}/></bufferGeometry><lineBasicMaterial color={voxel?'#ad96df':'#3e9cbe'} transparent opacity={voxel?.28:.16}/></lineSegments>{selectedPillar&&<mesh position={[selectedPillar.cx,(set.bounds.zmin+set.bounds.zmax)/2,-selectedPillar.cy]}><boxGeometry args={[set.size,set.bounds.zmax-set.bounds.zmin,set.size]}/><meshBasicMaterial color="#ffb267" transparent opacity={.18} depthWrite={false}/><lineSegments><edgesGeometry args={[selectedGeometry]}/><lineBasicMaterial color="#ffc184"/></lineSegments></mesh>}</>;
}
function FeatureLines({p,point,set}:{p:Pillar;point:Point;set:PillarSet}){ const mean:[number,number,number]=[p.mean[0],p.mean[2],-p.mean[1]],center:[number,number,number]=[p.cx,Math.max(0,set.bounds.zmin)+.02,-p.cy];return <><Line points={[pos(point),mean]} color="#ffb267" lineWidth={2}/><Line points={[pos(point),[p.cx,point.z,-p.cy],center]} color="#66dff3" lineWidth={2} dashed dashSize={.08} gapSize={.05}/>{[mean,center].map((v,i)=><mesh key={i} position={v}><sphereGeometry args={[.045,12,12]}/><meshBasicMaterial color={i?'#66dff3':'#ffb267'}/></mesh>)}<Html zIndexRange={[2,0]} position={mean} center style={{pointerEvents:'none'}}><span className="world-tag amber">Trung bình điểm</span></Html><Html zIndexRange={[2,0]} position={center} center style={{pointerEvents:'none'}}><span className="world-tag">Tâm ô x–y</span></Html></>;}
function BoundingBox({box,selected,labels,onBox}:{box:Box;selected:boolean;labels:boolean;onBox:(id:string)=>void}){const color=boxColor(box.label);const geometry=useMemo(()=>new THREE.BoxGeometry(box.l,box.h,box.w),[box.l,box.h,box.w]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <group position={pos(box)} rotation={[0,box.theta,0]}><mesh onClick={e=>{e.stopPropagation();onBox(box.id);}}><primitive object={geometry} attach="geometry"/><meshBasicMaterial color={color} transparent opacity={selected?.13:.025} depthWrite={false}/><lineSegments><edgesGeometry args={[geometry]}/><lineBasicMaterial color={color}/></lineSegments></mesh><Line points={[[0,-box.h/2+.03,0],[box.l/2+.5,-box.h/2+.03,0],[box.l/2+.23,-box.h/2+.03,.2],[box.l/2+.5,-box.h/2+.03,0],[box.l/2+.23,-box.h/2+.03,-.2]]} color={color} lineWidth={2}/>{labels&&<Html zIndexRange={[2,0]} position={[0,box.h/2+.35,0]} center style={{pointerEvents:'none'}}><span className="box-tag" style={{borderColor:color,color}}>{box.label}{box.confidence!==undefined?` · ${(box.confidence*100).toFixed(1)} %`:''}</span></Html>}</group>;}
function Heatmap({set,image}:{set:PillarSet;image:Float32Array}){const ref=useRef<THREE.InstancedMesh>(null);useEffect(()=>{if(!ref.current)return;const o=new THREE.Object3D(),c=new THREE.Color(),max=Math.max(.001,...set.pillars.map(p=>image[p.iy*set.width+p.ix]));set.pillars.forEach((p,i)=>{o.position.set(p.cx,.035,-p.cy);o.rotation.set(-Math.PI/2,0,0);o.updateMatrix();ref.current!.setMatrixAt(i,o.matrix);const t=image[p.iy*set.width+p.ix]/max;c.setRGB(.03+t*.9,.12+t*.65,.2+(1-t)*.28);ref.current!.setColorAt(i,c);});ref.current.instanceMatrix.needsUpdate=true;if(ref.current.instanceColor)ref.current.instanceColor.needsUpdate=true;},[set,image]);return <instancedMesh key={set.pillars.length} ref={ref} args={[undefined,undefined,set.pillars.length]}><planeGeometry args={[set.size*.92,set.size*.92]}/><meshBasicMaterial toneMapped={false}/></instancedMesh>;}
function Camera({step,top,reset,set,selectedPillar}:{step:number;top:boolean;reset:number;set:PillarSet;selectedPillar?:Pillar}){const focused=step===3?selectedPillar:undefined;const controls=useRef<OrbitImpl>(null);const {camera,invalidate}=useThree();const goal=useRef({p:new THREE.Vector3(),t:new THREE.Vector3(),active:true});useEffect(()=>{let target=new THREE.Vector3((set.bounds.xmin+set.bounds.xmax)/2,.5,-(set.bounds.ymin+set.bounds.ymax)/2);let span=Math.max(set.bounds.xmax-set.bounds.xmin,set.bounds.ymax-set.bounds.ymin);let p=target.clone().add(new THREE.Vector3(-span*.64,span*.68,span*.79));if(focused){target=new THREE.Vector3(focused.cx,(set.bounds.zmin+set.bounds.zmax)/2,-focused.cy);p=target.clone().add(new THREE.Vector3(-4.8,3.7,6.2));}if(top||step===5){p=target.clone().add(new THREE.Vector3(0,span*1.03,.2));}goal.current={p,t:target,active:true};invalidate();},[step,top,reset,set,focused,invalidate]);useFrame((_,delta)=>{if(goal.current.active&&controls.current){const a=1-Math.exp(-delta*7);camera.position.lerp(goal.current.p,a);controls.current.target.lerp(goal.current.t,a);controls.current.update();if(camera.position.distanceTo(goal.current.p)<.001)goal.current.active=false;invalidate();}});return <OrbitControls ref={controls} makeDefault enableDamping minDistance={.8} maxDistance={2500} maxPolarAngle={Math.PI*.497} onStart={()=>{goal.current.active=false;}}/>;}
function World(props:Props){const {step,set,selectedPillar,selectedPoint,points}=props;return <><color attach="background" args={['#0b1723']}/><fog attach="fog" args={['#0b1723',35,105]}/><ambientLight intensity={1}/><gridHelper args={[Math.max(30,set.bounds.xmax-set.bounds.xmin,set.bounds.ymax-set.bounds.ymin),30,'#254656','#182e3d']} position={[(set.bounds.xmin+set.bounds.xmax)/2,-.035,-(set.bounds.ymin+set.bounds.ymax)/2]}/><Camera {...props}/>{step!==5&&<Cloud {...props}/>}<mesh rotation={[-Math.PI/2,0,0]} position={[(set.bounds.xmin+set.bounds.xmax)/2,-.05,-(set.bounds.ymin+set.bounds.ymax)/2]}><planeGeometry args={[set.bounds.xmax-set.bounds.xmin,set.bounds.ymax-set.bounds.ymin]}/><meshBasicMaterial color="#0e202d"/></mesh>{(step===2||step===3)&&<Columns set={set} selectedPillar={selectedPillar} voxel={props.voxel} focus={step===3}/>} {step===3&&selectedPillar&&selectedPoint!==null&&points[selectedPoint]&&<FeatureLines p={selectedPillar} point={points[selectedPoint]} set={set}/>} {step===5&&<Heatmap set={set} image={props.image}/>} {step===6&&props.showBoxes&&props.boxes.map(b=><BoundingBox key={b.id} box={b} selected={b.id===props.selectedBox} labels={props.showLabels} onBox={props.onBox}/>)}<group position={[-10,.03,6.5]}><Line points={[[0,0,0],[2,0,0]]} color="#ffb267"/><Line points={[[0,0,0],[0,0,-2]]} color="#70efd1"/><Line points={[[0,0,0],[0,2,0]]} color="#5fd9f2"/>{[['x',[2.2,0,0]],['y',[0,0,-2.2]],['z',[0,2.2,0]]].map(([label,p])=><Html zIndexRange={[2,0]} key={label as string} position={p as [number,number,number]} center style={{pointerEvents:'none'}}><span className="axis-label">{label as string}</span></Html>)}</group></>;}
export default function SceneView(props:Props){return <Canvas camera={{position:[-16,17,20],fov:43,near:.01,far:10000}} dpr={[1,2]} gl={{antialias:true,preserveDrawingBuffer:true}} raycaster={{params:{Points:{threshold:.10},Line:{threshold:.05},Mesh:{},LOD:{},Sprite:{}}}}><World {...props}/></Canvas>;}
