import type { Box, Bounds, PredictionData, Point } from './types';
export function parsePredictions(raw:unknown):PredictionData {
  const fail=(m:string):never=>{throw new Error(m);};
  if(!raw||typeof raw!=='object'||Array.isArray(raw))return fail('File phải chứa một đối tượng JSON.');
  const d=raw as Record<string,unknown>; if(d.schemaVersion!==1)return fail('schemaVersion phải bằng 1.');
  if(!Array.isArray(d.points)||d.points.length===0||d.points.length>100000)return fail('points phải chứa từ 1 đến 100.000 điểm.');
  const finite=(v:unknown)=>typeof v==='number'&&Number.isFinite(v);
  const points:Point[]=d.points.map((v,i)=>{if(!v||typeof v!=='object')return fail(`points[${i}] không hợp lệ.`);const p=v as Record<string,unknown>;if(!['x','y','z','r'].every(k=>finite(p[k])))return fail(`points[${i}]: x, y, z, r phải là số hữu hạn.`);if((p.r as number)<0||(p.r as number)>1)return fail(`points[${i}].r phải thuộc [0, 1].`);if(['x','y','z'].some(k=>Math.abs(p[k] as number)>10000))return fail(`points[${i}]: tọa độ vượt quá ±10.000 m.`);return {x:p.x as number,y:p.y as number,z:p.z as number,r:p.r as number};});
  if(!Array.isArray(d.predictions)||d.predictions.length>500)return fail('predictions phải là mảng tối đa 500 hộp (có thể rỗng).');
  const ids=new Set<string>();
  const predictions:Box[]=d.predictions.map((v,i)=>{if(!v||typeof v!=='object')return fail(`predictions[${i}] không hợp lệ.`);const b=v as Record<string,unknown>;if(!['Car','Pedestrian','Cyclist'].includes(b.label as string))return fail(`predictions[${i}].label: dùng Car, Pedestrian hoặc Cyclist.`);if(!['x','y','z','w','l','h','theta'].every(k=>finite(b[k])))return fail(`predictions[${i}]: thiếu tọa độ, kích thước hoặc theta.`);if(['w','l','h'].some(k=>(b[k] as number)<=0||(b[k] as number)>10000))return fail(`predictions[${i}]: kích thước phải dương và ≤ 10.000 m.`);if(['x','y','z'].some(k=>Math.abs(b[k] as number)>10000))return fail(`predictions[${i}]: tọa độ vượt quá ±10.000 m.`);if(b.confidence!==undefined&&(!finite(b.confidence)||(b.confidence as number)<0||(b.confidence as number)>1))return fail(`predictions[${i}].confidence phải thuộc [0, 1].`);const id=b.id===undefined?`prediction-${i}`:b.id;if(typeof id!=='string'||ids.has(id))return fail(`predictions[${i}].id phải là chuỗi duy nhất.`);ids.add(id);return {id,label:b.label as Box['label'],x:b.x as number,y:b.y as number,z:b.z as number,w:b.w as number,l:b.l as number,h:b.h as number,theta:b.theta as number,...(b.confidence!==undefined?{confidence:b.confidence as number}:{})};});
  let metadata:PredictionData['metadata'];if(d.metadata!==undefined){if(!d.metadata||typeof d.metadata!=='object'||Array.isArray(d.metadata))return fail('metadata phải là đối tượng.');metadata={};for(const k of ['model','checkpoint','sample'] as const){const v=(d.metadata as Record<string,unknown>)[k];if(v!==undefined){if(typeof v!=='string'||v.length>500)return fail(`metadata.${k} phải là chuỗi tối đa 500 ký tự.`);metadata[k]=v;}}}
  const bounds:Bounds={xmin:Infinity,xmax:-Infinity,ymin:Infinity,ymax:-Infinity,zmin:Infinity,zmax:-Infinity};for(const p of [...points,...predictions]){bounds.xmin=Math.min(bounds.xmin,p.x-2);bounds.xmax=Math.max(bounds.xmax,p.x+2);bounds.ymin=Math.min(bounds.ymin,p.y-2);bounds.ymax=Math.max(bounds.ymax,p.y+2);bounds.zmin=Math.min(bounds.zmin,p.z-2);bounds.zmax=Math.max(bounds.zmax,p.z+2);}
  for(const b of predictions){const radius=Math.hypot(b.l,b.w)/2;bounds.xmin=Math.min(bounds.xmin,b.x-radius-1);bounds.xmax=Math.max(bounds.xmax,b.x+radius+1);bounds.ymin=Math.min(bounds.ymin,b.y-radius-1);bounds.ymax=Math.max(bounds.ymax,b.y+radius+1);bounds.zmin=Math.min(bounds.zmin,b.z-b.h/2-1);bounds.zmax=Math.max(bounds.zmax,b.z+b.h/2+1);}
  if((bounds.xmax-bounds.xmin)*(bounds.ymax-bounds.ymin)/(.16*.16)>4000000)return fail('Phạm vi x–y quá lớn để tạo lưới demo (tối đa 4 triệu ô ở 0,16 m).');
  return {schemaVersion:1,points,predictions,metadata,bounds};
}
