import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Box as BoxIcon, Check, ChevronDown, CircleHelp, Crosshair, Expand, ExternalLink, Grid2X2, Layers3, Maximize2, MousePointer2, Play, RotateCcw, ScanLine, Upload, X } from 'lucide-react';
import SceneView, { boxColor } from './components/SceneView';
import { BackbonePanel, NetworkPanel } from './components/NetworkPanel';
import { makeScene } from './core/synthetic';
import { groupPoints } from './core/pillars';
import { FEATURE_NAMES, pointFeatures } from './core/features';
import { encodeAll } from './core/encoder';
import { scatterChannel } from './core/scatter';
import { parsePredictions } from './core/import';
import { DEMO_BOUNDS, MAX_PILLARS, MAX_POINTS } from './core/types';
import type { PredictionData } from './core/types';
import { STEPS } from './content';
const fmt=(v:number)=>v.toLocaleString('vi-VN');
export default function App(){
  const [step,setStep]=useState(1),[sceneId,setSceneId]=useState(0),[size,setSize]=useState(.32),[top,setTop]=useState(false),[reset,setReset]=useState(0),[voxel,setVoxel]=useState(false),[pointId,setPointId]=useState<number|null>(null),[pillarKey,setPillarKey]=useState<string|null>(null),[boxId,setBoxId]=useState<string|null>(null),[channel,setChannel]=useState(0),[showBoxes,setShowBoxes]=useState(true),[showLabels,setShowLabels]=useState(true),[mode,setMode]=useState<'synthetic'|'model'>('synthetic'),[imported,setImported]=useState<PredictionData|null>(null),[importError,setImportError]=useState(''),[help,setHelp]=useState(false),[presenting,setPresenting]=useState(false),[notice,setNotice]=useState('');
  const input=useRef<HTMLInputElement>(null);
  const scene=useMemo(()=>makeScene(sceneId),[sceneId]);const isModel=step===6&&mode==='model';
  const points=isModel?(imported?.points??[]):scene.points,boxes=isModel?(imported?.predictions??[]):scene.boxes,bounds=isModel?(imported?.bounds??DEMO_BOUNDS):DEMO_BOUNDS;
  const set=useMemo(()=>groupPoints(points,size,bounds),[points,size,bounds]);
  const defaultPillar=useMemo(()=>[...set.pillars].filter(p=>p.mean[2]>.3).sort((a,b)=>b.indices.length-a.indices.length)[0]??set.pillars[0],[set]);
  const pillar=(pillarKey?set.lookup.get(pillarKey):undefined)??defaultPillar;
  const activePoint=pointId!==null&&(step===1||pillar?.indices.includes(pointId))?pointId:(step===3||step===4?pillar?.sampled[0]??null:null);
  const point=activePoint!==null?points[activePoint]:undefined;
  const features=point&&pillar?pointFeatures(point,pillar):null;
  const box=boxes.find(b=>b.id===boxId);
  const vectors=useMemo(()=>step===5?encodeAll(set.pillars,points):new Map<string,number[]>(),[step,set,points]);
  const image=useMemo(()=>step===5?scatterChannel(set,vectors,channel):new Float32Array(0),[step,set,vectors,channel]);
  const clearSelection=useCallback(()=>{setPointId(null);setPillarKey(null);setBoxId(null);},[]);
  const go=useCallback((n:number)=>{setStep(Math.min(6,Math.max(1,n)));setTop(false);setReset(r=>r+1);},[]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(help)setHelp(false);if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});return;}if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement||help)return;if(e.key==='ArrowRight'){e.preventDefault();go(step+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(step-1);}if(e.key.toLowerCase()==='r'){setReset(r=>r+1);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[go,step,help]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t);},[notice]);
  const changeScene=(n:number)=>{clearSelection();setSceneId(n);setReset(r=>r+1);};
  const choosePoint=(i:number)=>{setPointId(i);setPillarKey(set.pointKeys.get(i)??null);};
  const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setNotice('Trình duyệt chặn toàn màn hình. Có thể dùng phím F11.');}};
  const load=async(file?:File)=>{if(!file)return;setImportError('');try{if(file.size>30*1024*1024)throw new Error('File vượt quá giới hạn 30 MB.');const data=parsePredictions(JSON.parse(await file.text()));setImported(data);clearSelection();setMode('model');setReset(r=>r+1);setNotice(`Đã nạp ${fmt(data.points.length)} điểm và ${data.predictions.length} hộp.`);}catch(e){setImportError(e instanceof SyntaxError?'JSON không hợp lệ: kiểm tra dấu ngoặc và dấu phẩy.':e instanceof Error?e.message:'Không đọc được file.');}if(input.current)input.current.value='';};
  const downloadSchema=()=>{const data={schemaVersion:1,metadata:{model:'Tên mô hình của bạn',checkpoint:'Đường dẫn / mã checkpoint',sample:'Mã mẫu dữ liệu'},points:[{x:0,y:0,z:0,r:.5}],predictions:[]};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='prediction-format.json';a.click();URL.revokeObjectURL(url);};
  const content=STEPS[step-1];
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();go(1);}}><span className="brand-icon"><Layers3 size={24}/></span><span>Point<span className="brand-light">Pillars</span><small>INTERACTIVE EXPLORER</small></span></a><span className="header-divider"/><span className="header-subtitle">Từ điểm đến nhận thức<span>Khám phá phát hiện vật thể 3D</span></span><div className="header-actions"><label className="scene-select"><ScanLine size={16}/><select aria-label="Chọn cảnh" value={sceneId} disabled={isModel} onChange={e=>changeScene(Number(e.target.value))}><option value={0}>01 · Đường phố đô thị</option><option value={1}>02 · Xe đạp & cột đèn</option><option value={2}>03 · Xa & che khuất</option></select><ChevronDown size={14}/></label><button className="icon-button" title="Đặt lại góc nhìn (R)" aria-label="Đặt lại góc nhìn" onClick={()=>setReset(r=>r+1)}><RotateCcw size={18}/></button><button className="icon-button" title="Toàn màn hình" aria-label="Toàn màn hình" onClick={toggleFullscreen}><Expand size={18}/></button><button className="icon-button" title="Hướng dẫn & nguồn" aria-label="Hướng dẫn và nguồn" onClick={()=>setHelp(true)}><CircleHelp size={18}/></button><button className={'primary-button '+(presenting?'presenting':'')} onClick={()=>{setPresenting(p=>!p);if(!presenting){go(1);setNotice('Đã bắt đầu · dùng ← → để chuyển bước.');}}}>{presenting?<Check size={15}/>:<Play size={15} fill="currentColor"/>}{presenting?'Đang trình diễn':'Bắt đầu trình diễn'}</button></div></header>
    <main className="main-layout"><section className="visual-section" aria-label="Trực quan hóa 3D">
      <div className="scene-heading"><div><div className="eyebrow"><span className="status-dot"/> KHÔNG GIAN KHÁM PHÁ <span className="scene-index">/ 0{sceneId+1}</span></div><h1>{step===3?'Khám phá bên trong một pillar':step===4?'Mã hóa cấu trúc cục bộ':step===5?'Từ không gian 3D đến lưới 2D':isModel?(imported?'Kết quả suy luận đã nạp':'Kết quả mô hình'):scene.name}</h1></div><span className={'data-badge '+(isModel?'model-badge':'')}><span/>{isModel?(imported?'Dữ liệu nhập từ JSON':'Chưa nạp dữ liệu'):'Dữ liệu tổng hợp minh họa'}</span></div>
      <div className="viewport"><SceneView points={points} boxes={boxes} set={set} step={step} selectedPillar={pillar} selectedPoint={activePoint} selectedBox={boxId} onPoint={choosePoint} onBox={setBoxId} top={top} reset={reset} voxel={voxel} showBoxes={showBoxes} showLabels={showLabels} image={image} channel={channel} model={isModel}/>
        <div className="viewport-top"><div className="view-switch"><button className={!top&&step!==5?'active':''} onClick={()=>{setTop(false);setReset(r=>r+1);}} disabled={step===5}><BoxIcon size={14}/> Phối cảnh</button><button className={top||step===5?'active':''} onClick={()=>{setTop(true);setReset(r=>r+1);}}><Grid2X2 size={14}/> Từ trên xuống</button></div><span className="unit-label">TỌA ĐỘ MÉT · Z ↑</span></div>
        {(step===1||step===2||step===6)&&<div className="scene-legend">{step===6?<><span><i style={{background:'#ffb267'}}/>Car</span><span><i style={{background:'#70efd1'}}/>Pedestrian</span><span><i style={{background:'#c8a2ff'}}/>Cyclist</span></>:<><span><i/>Điểm vật thể</span><span><i className="ground"/>Mặt đường</span>{step===2&&<span><i className="amber-dot"/>{voxel?'Voxel chia x, y, z':'Pillar được chọn'}</span>}</>}</div>}
        {step===4&&<NetworkPanel pillar={pillar} points={points}/>}{step===5&&<BackbonePanel/>}
        {isModel&&!imported&&<div className="empty-model"><Upload size={35}/><h2>Chưa nạp kết quả suy luận</h2><p>Nạp point cloud và dự đoán tương ứng từ cùng một file JSON.</p><button className="primary-button" onClick={()=>input.current?.click()}>Chọn file JSON</button></div>}
        <div className="viewport-bottom"><span><MousePointer2 size={13}/> Kéo để xoay <b>·</b> Cuộn để zoom <b>·</b> Chuột phải để dịch</span><span className="point-count">{fmt(points.length)} điểm <span> / {step===5?'64 kênh':'XYZ + R'}</span></span></div>
      </div>
      <div className="narration"><span className="narration-icon">“</span><div><span className="eyebrow">GỢI Ý THUYẾT TRÌNH</span><p>{isModel?(imported?'“Các hộp này đến từ file kết quả đã nhập. Nguồn mô hình và confidence chỉ xuất hiện khi dữ liệu cung cấp.”':'“Nạp point cloud và kết quả đã tính sẵn để quan sát. Hiện chưa có dữ liệu suy luận trong chế độ này.”'):content.cue}</p></div><span className="duration">~30 giây</span></div>
    </section>
    <aside className={`sidebar step-${step}`}><div className="step-heading"><span className="step-number">0{step}</span><div><span className="eyebrow">BƯỚC {step} / 6</span><span className="english-title">{content.english}</span></div><span className="mini-line"/></div><h2>{content.title}</h2><p className="description">{isModel?'Xem các hộp dự đoán đã tính sẵn cùng point cloud tương ứng. Frontend không thực hiện suy luận.':content.description}</p><ul className="key-points">{content.bullets.map((b,i)=><li key={b}><span>0{i+1}</span>{b}</li>)}</ul><div className="section-divider"/>
      {step===1&&<><div className="panel-label"><Crosshair size={14}/> ĐIỂM ĐANG CHỌN <span>{point?'Đã chọn':'Chờ chọn'}</span></div>{point?<div className="values-grid">{['x','y','z','r'].map(k=><div key={k}><label>{k}</label><b>{point[k as 'x'].toFixed(3)}<small>{k==='r'?'':' m'}</small></b></div>)}</div>:<button className="selection-prompt" onClick={()=>{if(pillar)choosePoint(pillar.sampled[0]);}}><MousePointer2 size={21}/><span>Nhấp vào một điểm trong cảnh<small>hoặc chọn điểm mẫu để bắt đầu</small></span><ArrowRight size={16}/></button>}<div className="concept-card"><span>ĐẦU VÀO CỦA MÔ HÌNH</span><div className="input-vector">[ <b>x</b>, <b>y</b>, <b>z</b>, <em>r</em> ]</div><p>Không có bề mặt liên tục; mỗi điểm là một phép đo LiDAR rời rạc.</p></div></>}
      {(step===2||step===3)&&<><div className="panel-label"><Grid2X2 size={14}/> CẠNH Ô PILLAR <span>{size.toFixed(2).replace('.',',')} m</span></div><input aria-label="Kích thước pillar" className="size-slider" type="range" min={0} max={3} step={1} value={[.16,.24,.32,.48].indexOf(size)} onChange={e=>{clearSelection();setSize([.16,.24,.32,.48][Number(e.target.value)]);}}/><div className="slider-labels">{[.16,.24,.32,.48].map(s=><button key={s} className={s===size?'active':''} onClick={()=>{clearSelection();setSize(s);}}>{s.toFixed(2).replace('.',',')}</button>)}</div>{step===2&&<><div className="stats-rows"><div><span>Pillar không rỗng</span><b data-testid="pillar-count">{fmt(set.totalNonempty)}</b></div><div><span>Kích thước lưới</span><b>{set.width} × {set.height}</b></div><div><span>Điểm / pillar không rỗng</span><b>{(set.validPointCount/Math.max(1,set.totalNonempty)).toFixed(2)}</b></div></div><label className="toggle-row"><span>So sánh với voxel<small>Voxel chia thêm theo chiều z</small></span><input type="checkbox" checked={voxel} onChange={e=>setVoxel(e.target.checked)}/></label><p className="fine-print">Pillar lớn giảm số ô và độ phân giải không gian. Các giá trị trên không suy ra AP hay tốc độ mô hình.</p></>}{step===3&&features&&pillar&&<><div className="feature-vector-label">VECTOR ĐIỂM <span>9 CHIỀU</span></div><div className="feature-table">{FEATURE_NAMES.map((name,i)=><div key={name} className={i>6?'pillar-offset':i>3?'mean-offset':''}><label>{name}</label><b>{features[i].toFixed(4)}</b></div>)}</div><div className="formula-note">x_c = x − mean_x · y_c = y − mean_y<br/>z_c = z − mean_z<br/>x_p = x − tâm_x · y_p = y − tâm_y</div><label className="point-select">Điểm thật trong pillar<select aria-label="Điểm trong pillar" value={activePoint??''} onChange={e=>choosePoint(Number(e.target.value))}>{pillar.sampled.map((v,i)=><option value={v} key={v}>Điểm {i+1} · z = {points[v].z.toFixed(3)} m</option>)}</select></label><div className="padding-note">{pillar.indices.length} điểm thật · giữ {pillar.sampled.length}/{MAX_POINTS}<br/>{Math.max(0,MAX_POINTS-pillar.sampled.length)} hàng zero padding; không vẽ tại gốc.<br/>Dư {MAX_POINTS} điểm: lấy mẫu bằng seed cố định.</div></>}</>}
      {step===4&&<><div className="panel-label"><Layers3 size={14}/> KÍCH THƯỚC TENSOR</div><div className="tensor-shapes"><span>(9, P, N)</span><ArrowRight size={14}/><span>(64, P, N)</span><ArrowRight size={14}/><span>(64, P)</span></div><p className="fine-print">P = {fmt(set.pillars.length)} pillar được giữ lại<br/>N = {MAX_POINTS} điểm tối đa / pillar</p><div className="simulation-note"><span className="amber-dot"/>Mô phỏng phép biến đổi — chưa sử dụng trọng số đã huấn luyện.</div><div className="concept-card"><span>GỘP THEO CHIỀU ĐIỂM</span><p>Mỗi điểm đi qua cùng một Linear. Max pooling chọn giá trị lớn nhất cho từng kênh trong tất cả điểm thật được giữ lại.</p></div></>}
      {step===5&&<><div className="panel-label"><Layers3 size={14}/> KÊNH ĐẶC TRƯNG <span>{channel+1} / 64</span></div><select className="channel-select" aria-label="Kênh đặc trưng" value={channel} onChange={e=>setChannel(Number(e.target.value))}>{Array.from({length:64},(_,c)=><option key={c} value={c}>Kênh {String(c+1).padStart(2,'0')} · phép mã hóa mô phỏng</option>)}</select><div className="heat-legend"><span>0</span><i/><span>Max kênh</span></div><div className="stats-rows"><div><span>Pseudo-image</span><b>64 × {set.height} × {set.width}</b></div><div><span>Ô không có pillar</span><b>Giá trị 0</b></div></div><div className="simulation-note"><span className="amber-dot"/>Đặc trưng mô phỏng với trọng số cố định; chưa phải đặc trưng đã học.</div><p className="fine-print">Sơ đồ nhiều tỉ lệ chỉ minh họa kiến trúc, không thực thi CNN 2D.</p></>}
      {step===6&&<><div className="mode-switch"><button className={mode==='synthetic'?'active':''} onClick={()=>{clearSelection();setMode('synthetic');}}>Minh họa</button><button className={mode==='model'?'active':''} onClick={()=>{clearSelection();setMode('model');}}>Kết quả mô hình</button></div><p className="source-note">{isModel?(imported?'Nguồn: file JSON do người dùng cung cấp':'Chưa có dữ liệu dự đoán được nạp'):'Hộp tham chiếu của cảnh tổng hợp'}</p><div className="display-options"><label><input type="checkbox" checked={showBoxes} onChange={e=>setShowBoxes(e.target.checked)}/> Hộp bao</label><label><input type="checkbox" checked={showLabels} onChange={e=>setShowLabels(e.target.checked)}/> Nhãn</label></div>{(!isModel||imported)&&<div className="object-list">{boxes.map(b=><button key={b.id} onClick={()=>setBoxId(b.id)} className={boxId===b.id?'active':''}><i style={{background:boxColor(b.label)}}/><span>{b.label}<small>{b.id}</small></span><ArrowRight size={14}/></button>)}{boxes.length===0&&<p className="fine-print">Mẫu này không có hộp dự đoán.</p>}</div>}{box&&<div className="box-values">{['x','y','z','w','l','h','theta'].map(k=><div key={k}><label>{k==='theta'?'θ':k}</label><b>{box[k as 'x'].toFixed(3)}<small>{k==='theta'?' rad':' m'}</small></b></div>)}{box.confidence!==undefined&&<div><label>confidence</label><b>{box.confidence.toFixed(4)}</b></div>}</div>}{isModel&&<><button className="upload-button" onClick={()=>input.current?.click()}><Upload size={15}/>{imported?'Nạp file JSON khác':'Nạp kết quả JSON'}</button><button className="text-button" onClick={downloadSchema}><ArrowDownToLine size={13}/>Tải mẫu định dạng (không có dự đoán)</button>{imported?.metadata&&<div className="metadata">{Object.entries(imported.metadata).map(([k,v])=><p key={k}><span>{k}</span>{v}</p>)}</div>}</>}{importError&&<p role="alert" className="error-message">{importError}</p>}</>}
      <div className="sidebar-bottom"><span className="small-dot"/>DEMO · P ≤ {fmt(MAX_PILLARS)} · N = {MAX_POINTS}<p>Bài báo: 0,16 m · P ≤ 12.000 · N = 100</p></div>
    </aside></main>
    <footer className="bottom-nav"><div className="nav-caption"><span>QUY TRÌNH</span><b>PointPillars</b></div><nav aria-label="Các bước xử lý">{STEPS.map((s,i)=><button key={s.short} className={step===i+1?'active':step>i+1?'complete':''} onClick={()=>go(i+1)} aria-label={`Bước ${i+1}: ${s.short}`}><span>{step>i+1?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><b>{s.short}</b></button>)}</nav><div className="nav-arrows"><button aria-label="Bước trước" disabled={step===1} onClick={()=>go(step-1)}><ArrowLeft size={17}/></button><button aria-label={step===6?'Về bước đầu':'Bước tiếp theo'} onClick={()=>go(step===6?1:step+1)}><ArrowRight size={17}/></button></div><div className="progress-track"><div style={{width:`${step/6*100}%`}}/></div></footer>
    <div className="app-footnote"><span>POINTPILLARS · LANG ET AL., 2019</span><a href="https://arxiv.org/abs/1812.05784" target="_blank" rel="noreferrer">arXiv:1812.05784 <ExternalLink size={11}/></a><span><kbd>←</kbd><kbd>→</kbd> Chuyển bước <i/> <kbd>R</kbd> Đặt lại góc nhìn</span></div>
    <input ref={input} type="file" accept=".json,application/json" aria-label="File kết quả suy luận" hidden onChange={e=>void load(e.target.files?.[0])}/>
    {notice&&<div role="status" className="toast"><Check size={16}/>{notice}</div>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-label="Hướng dẫn" onClick={e=>e.stopPropagation()}><button className="close-modal icon-button" aria-label="Đóng hướng dẫn" onClick={()=>setHelp(false)}><X size={19}/></button><span className="eyebrow">POINTPILLARS EXPLORER</span><h2>Một hành trình từ điểm đến hộp 3D.</h2><p>Dành khoảng 30 giây cho mỗi bước. Chọn điểm, đổi kích thước pillar, quan sát vector 9 chiều và theo dõi scatter về pseudo-image.</p><div className="help-shortcuts"><span><MousePointer2/>Kéo xoay · cuộn zoom · chuột phải dịch</span><span><ArrowRight/>← → chuyển bước · R đặt lại camera</span><span><Maximize2/>Toàn màn hình · Escape để thoát</span></div><p>Toàn bộ cảnh được sinh bằng seed cố định. PFN dùng trọng số cố định để giải thích. Backbone và detection head là minh họa kiến trúc. Không chạy huấn luyện hay suy luận trong trình duyệt.</p><p>Cấu hình demo: cạnh ô mặc định 0,32 m, tối đa {fmt(MAX_PILLARS)} pillar và {MAX_POINTS} điểm/pillar. Mục 4.2 của bài báo dùng 0,16 m, 12.000 pillar và 100 điểm/pillar.</p><a className="paper-link" href="https://arxiv.org/abs/1812.05784" target="_blank" rel="noreferrer">PointPillars: Fast Encoders for Object Detection from Point Clouds <ExternalLink size={16}/></a><button className="primary-button" onClick={()=>setHelp(false)}>Bắt đầu khám phá <ArrowRight size={15}/></button></section></div>}
  </div>;
}
